name:                polysemy-es
version:             0.1.0.0
github:              "Lando-L/polysemy-es"
license:             BSD3
author:              "Lando"
maintainer:          "example@example.com"
copyright:           "2022 Lando"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Lando-L/polysemy-es#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- polysemy
- polysemy-plugin
- polysemy-zoo
- text

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -fplugin=Polysemy.Plugin

library:
  source-dirs: src

tests:
  polysemy-es-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - polysemy-es
    - hspec
    - hspec-contrib
    - QuickCheck
